#!/usr/bin/env bash
#script hat displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

i=0
j=1

while [ "$1" -le 12 ]; do
	echo "Hour: $i"
	while [ $j -le 59 ]; do
		echo $j
		j=$((j+1))
	done
	j=$((1))
	i=$((i+1))
done
